spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5442/inventories
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8082
